packages:
  - client/*
  - packages/*
  - protocol/*

catalog:
  '@commitlint/cli': 19.8.1
  '@commitlint/config-conventional': 19.8.1
  '@eslint/js': ^9.34.0
  '@neondatabase/serverless': ^1.0.2
  '@next/eslint-plugin-next': ^15.5.0
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-query': ^5.66.5
  '@tanstack/react-query-devtools': ^5.84.2
  '@tanstack/react-router': ^1.132.0
  '@tanstack/react-router-devtools': ^1.132.0
  '@tanstack/router-plugin': ^1.132.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.2.0
  '@types/node': ^22.10.2
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  '@vitejs/plugin-react': ^5.0.4
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  eslint: ^9.34.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.3.0
  hono: ^4.9.12
  husky: 9.1.7
  jsdom: ^27.0.0
  lint-staged: ^16.1.5
  lucide-react: ^0.545.0
  neonctl: ^2.15.1
  prettier: ^3.6.2
  react: ^19.0.0
  react-dom: ^19.0.0
  rimraf: ^6.0.1
  tailwindcss: ^4.0.6
  tsx: ^4.20.6
  turbo: ^2.5.8
  typescript: ^5.9.2
  typescript-eslint: ^8.40.0
  vite: ^7.1.7
  vitest: ^3.0.5
  web-vitals: ^5.1.0

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
